version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres
    restart: always
    ports:      
      - 5433 :5433 
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
    

volumes:
  pgdata:
  redisdata:
